name: CI

on:
  push:
    branches: [ task4 ]
  pull_request:
    branches: [ task4 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir 3rdparty
        cd 3rdparty
        git clone https://github.com/google/googletest.git
        cd ..
        mkdir build
        cd build
        export GOOGLE_TEST_DIR=googletest
        cmake -DCMAKE_INSTALL_PREFIX=/home/runner/work/Temp/Temp ..
        make
        make install

    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: "../../bin/CTestExe"
        report-path: "report.xml"
        working-directory: "task4/"

    - name: UploadArtifacts
      uses: actions/upload-artifact@v1
      with:
        name: Distributive
        path: /home/runner/work/Temp/Temp/exe
